no_co2_network:
  sector:
    co2_network: false

frozen_H2_27:
# only h2 network with projects until 2027 are added
# no more expansion of the h2 grid allowed
  wasserstoff_kernnetz:
    enable: true
    cutoff_year: 2027
    force_all_ipcei_pci: false
  sector:
    H2_network: false

endo_H2:
# endogenous optimization of h2 network
# see if co-optimizing leads to more co2 pipelines
  wasserstoff_kernnetz:
    enable: false
    force_all_ipcei_pci: false

pcipmi_H2_+:
# forcing all pcipmi projects
# endogenous extension of H2 allowed

onshore_sequestration:
# onshore sequestration of co2 allowed
  sector:
    regional_co2_sequestration_potential:
      enable: true
      attribute:
      - optimistic estimate Mt
      - optimistic estimate GAS Mt
      - optimistic estimate OIL Mt
      - optimistic estimate aquifer Mt
      include_onshore: true

low_seq_potential:
# lower volume for sequestration available
  sector:
    co2_sequestration_potential:
      2030: 20
      2035: 50
      2040: 90
      2045: 125
      2050: 125

high_seq_potential:
# higher volume for sequestration available
  sector:
    co2_sequestration_potential:
      2030: 80
      2035: 200
      2040: 360
      2045: 500
      2050: 500

low_gas_price:
# gas price of 50 % of standard price
  costs:
    gas_price_factor: 0.5

high_gas_price:
# gas price of 200 % of standard price
  costs:
    gas_price_factor: 2.0

low_seq_cost:
# sequestration cost of 50 % of standard cost
  sector:
    co2_sequestration_cost: 17.5

high_seq_cost:
# sequestration cost of 200 % of standard cost
  sector:
    co2_sequestration_cost: 70

european_relocation:
# import of meoh, NH3, hbi from Europe
  sector:
    industry_relocation: true

non_european_relocation:
# import of meoh, NH3, hbi from Europe
# and non-European countries
  sector:
    industry_relocation: true
    imports:
      enable: true
      limit: .inf
      limit_sense: <=
      price:
        NH3:
          2035: 113
          2045: 98
        methanol:
          2035: 138
          2045: 120
        hbi:
          2035: 462
          2045: 438

no_early_retirement:
  sector:
    bof_retirement_date: false