no_co2_network:
  sector:
    co2_network: true # deactivated in solve_network
  carrier_networks:
    CO2:
      enable: false

frozen_H2_28:
# only h2 network with projects until 2027 are added
# no more expansion of the h2 grid allowed
  wasserstoff_kernnetz:
    enable: true
    cutoff_year: 2028
    force_all_ipcei_pci: false
  sector:
    H2_network: true # deactivated in solve_network
  carrier_networks:
    CO2:
      enable: true
    H2:
      enable: true
      options:
        delay: 6 # build_year + delay < planning_horizon

endo_H2:
# endogenous optimization of h2 network
# see if co-optimizing leads to more co2 pipelines
  wasserstoff_kernnetz:
    enable: false
    force_all_ipcei_pci: false
  carrier_networks:
    CO2:
      enable: false
    H2:
      enable: false

pcipmi_H2_+:
# forcing all pcipmi projects
# endogenous extension of H2 allowed
  carrier_networks:
    CO2:
      enable: true
      options:
        delay: 0 # build_year + delay < planning_horizon
    H2:
      enable: true
      options:
        delay: 0 # build_year + delay < planning_horizon

onshore_sequestration:
# onshore sequestration of co2 allowed
  sector:
    regional_co2_sequestration_potential:
      enable: true
      attribute:
      - optimistic estimate Mt
      - optimistic estimate GAS Mt
      - optimistic estimate OIL Mt
      - optimistic estimate aquifer Mt
      include_onshore: true

no_early_retirement:
  sector:
    bof_retirement_date: false

seq_90:
  sector:
    co2_sequestration_potential:
      2035: 90

seq_80:
  sector:
    co2_sequestration_potential:
      2035: 80

seq_70:
  sector:
    co2_sequestration_potential:
      2035: 70

seq_60:
  sector:
    co2_sequestration_potential:
      2035: 60

seq_50:
  sector:
    co2_sequestration_potential:
      2035: 50

northern_lights:
# remove sequestration potential in North Sea for Germany
# Add shipping route Germany - Northern Lights
# Done in modify_prenetwork