topo_1500km:
  co2_topology:
    length_limit_km: 1500
    alpha_values:
      - 0
      - 2
    pruning_rounds: 3

topo_1000km:
  co2_topology:
    length_limit_km: 1000
    alpha_values:
      - 0
      - 2
    pruning_rounds: 3

topo_500km:
  co2_topology:
    length_limit_km: 500
    alpha_values:
      - 0
      - 2
    pruning_rounds: 3
